# Generated by Django 3.2 on 2021-05-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_message', models.CharField(max_length=255)),
                ('output_message', models.TextField()),
                ('next_question', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tarot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField()),
                ('card_image', models.ImageField(upload_to='')),
                ('explanation', models.TextField()),
            ],
        ),
    ]
