# Generated by Django 3.2 on 2021-05-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_remove_tarot_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarot',
            name='card_image',
            field=models.ImageField(default='R0lGODlhAQABAIAAAP///////yH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==', upload_to=''),
            preserve_default=False,
        ),
    ]
